
camera:
    id: 0
    fovh: 75
    w: 5120
    h: 800
    c: 3
    pformat: BA81
    wr: 2560

marker:
   family: 36h11
   size: 0.18
   ids: [1,2,3,4,5,6,7,8]

display:
    main: True
    marker: True
    objdet: True

FPS:
    org: [20, 30]
    fontscale: 1
    color: [0,255,255]
    thickness: 1

